a = float(input("Nhập giá trị của a: "))
b = float(input("Nhập giá trị của b: "))
c = float(input("Nhập giá trị của c: "))
d = float(input("Nhập giá trị của d: "))
max = max(a, b, c, d)
min = min(a, b, c, d)
print("Max=", max)
print("Min=", min)